pool:
  vmImage: 'Ubuntu 16.04'

variables:
  - group: Docker

steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.2.203'
    inputs:
      version: 2.2.203

  - script: chmod -R a+x scripts
    displayName: 'chmod -R a+x scripts'

  - task: Bash@3
    displayName: 'DockerBuild'
    inputs:
      targetType: 'filePath'
      filePath: "./scripts/azrue-pipelines.sh"
      arguments: All
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      ORGANIZATION_NAME: $(ORGANIZATION_NAME)
      BUILD_SOURCEBRANCH: $(Build.SourceBranch)
      BUILD_BUILDNUMBER: $(Build.BuildNumber)
      BUILD_NUMBER: $(Build.BuildNumber)
      REPOSITORY_NAME: $(Build.Repository.Name)