version: '3.7'
services:
  catalogdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - catalogdb_container:/data/db

volumes:
  catalogdb_container: