version: '3.7'
services:
  catalogdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - catalogdb_container:/data/db
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - products:/opt/solr/server/solr/products:
volumes:
  catalogdb_container:
  products: